name: TestRun

on:
  schedule:
    # Run at every 12 hours
    - cron: '0 */12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Install Cypress
        run: npm install cypress --save-dev
      
      - name: Install dependencies
        run: npm install

      - name: Create reports directory
        run: mkdir -p cypress/reports

      - name: Create videos directory
        run: mkdir -p cypress/videos

      - name: Run Cypress tests
        run: npm run cy:run -- --headless --browser chrome --reporter junit --reporter-options "mochaFile=cypress/reports/test-results-[hash].xml"
        continue-on-error: true
        
      - name: List test results directory
        run: |
         if [ -d "cypress/reports" ]; then
          ls -la cypress/reports
         else
          echo "No test reports directory found."
         fi

      - name: List test videos directory
        run: |
         if [ -d "cypress/videos" ]; then
          ls -la cypress/videos
         else
          echo "No test videos directory found."
         fi

      - name: Always upload test reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: cypress/reports
